documentation/docusaurus.config.js

Fix the URL in docusaurus
Close: #106 

docs: Fix URL

---

.github/workflows/deploy-documentation.yaml
.github/workflows/publish.yaml

Fix workflow triggers and release environment config.
Fix workflows

ci: Fix workflows

---

.github/workflows/check-ert-integration.yaml

Update python version in check-ert-integration.yaml
Komodo will default to python 3.11 soon.

ci: Update python version in check-ert-integration.yaml

---

.github/workflows/release-please.yaml

Fix a typo in the outputs from release-please workflow
Close: #XXX

ci(workflow): Fix typo in release-please workflow output

---

.github/workflows/conventional-pr-title.yaml

ci: Skip capitalized check for release please branch

---

documentation/package.json
documentation/yarn.lock

Update dependencies.
SNYK reported warnings with current versions.
Updated requirments.
Close: #XXX

fix(security): Update dependencies for build

---

completor/create_output.py
completor/read_casefile.py

Simple renames.
Improves readability. Easier to follow where code originates.
Close: #XXX

refactor: Rename aliased imports `val` & `po` to their non-aliased names

---

completor/create_output.py
completor/main.py
completor/visualization.py

Make `PdfPages` context managed instead of manually opened and closed.
Less mess.
Close: #XXX

chore: Make pdf figure context managed

---

completor/completion.py
completor/constants.py
completor/create_output.py
completor/create_wells.py
completor/input_validation.py
completor/prepare_outputs.py
completor/read_casefile.py
completor/read_schedule.py
completor/visualize_well.py
tests/completor/test_completion.py
tests/completor/test_missing_keywords.py
tests/completor/test_prepare_outputs.py
tests/completor/test_read_casefile.py

Add more constants denoting literal values found in data.
Ease of maintenance, and verbosity.
Implement new frozen class `_Content`
Close: #XXX

refactor: Constants content

---

documentation/package.json
documentation/yarn.lock

build: Bump docusaurus dependencies

---

completor/create_output.py
completor/main.py
completor/prepare_outputs.py
completor/wells.py

Due to changes (not released) the schedule file got duplicate `WELSPECS` keywords.
This PR fixes these problems.
Tests assuring this issue can't reoccur are following in a separate PR.
Close: #XXX

fix: Fix duplicate welspecs

---

completor/create_output.py
completor/main.py
completor/prepare_outputs.py
completor/wells.py

perf: Use list append when string building

---

release-please-config.json

Makes more conventional commit formats visible for release-please.
Close: #110

chore: Make more conventional commit formats not hidden from release-please

---

completor/completion.py
completor/utils.py
completor/wells.py

- Replace method with `CompletorError`.
- Remove old (and now unused) `log_and_raise_exception`.
- Remove redundant, worse duplicate of error message.
Better error report, cleaner code.
N/A
Close: #XXX

chore: Improved error message

---

completor/completion.py
completor/create_output.py
completor/exceptions/__init__.py
completor/input_validation.py
completor/main.py
completor/prepare_outputs.py
completor/read_casefile.py
completor/utils.py
tests/completor/test_completion.py
tests/completor/test_create_wells.py
tests/completor/test_input_validation.py
tests/completor/test_lateral_routing.py
tests/completor/test_missing_keywords.py
tests/completor/test_read_casefile.py
tests/completor/test_use_strict.py
tests/completor/utils_for_tests.py

Replaced error-prone import handling with the full imports.
Make it possible to import parse from Completor in another project.
Close: #XXX

fix: Partially initialized module

---

completor/main.py
poetry.lock

Minor fix for poetry lock and import.
Close: #XXX

chore: Update poetry.lock

---

completor/create_output.py

Reverting update_segment to previous version
It should not raise error if df_device is empty, as it raised warning already
Close: #193 

fix: Revert after refactor

---

.github/workflows/check-ert-integration.yaml
.github/workflows/tests.yaml
README.md
poetry.lock
pyproject.toml

Add python 3.12 suppport in poetry and github-workflows.
To support more (and faster) versions, increase compatability.
Close: #212

chore: Add support for python 3.12

---

poetry.lock
pyproject.toml

fix: Python versions in `pyproject.toml`

---

.github/workflows/check-ert-integration.yaml
.github/workflows/tests.yaml
README.md
poetry.lock
pyproject.toml

Seems to break release-please
Close: #XXX

revert: Python3.12 update since it breaks release-please

---

.github/workflows/conventional-pr-title.yaml

chore: Temporary disable check for title until modified

---

completor/completion.py
tests/completor/data/icv_valve.case
tests/completor/data/icv_valve.true
tests/completor/test_main.py

Check if there are two WSEGVALV-es due to ICV and nozzle ICD not to duplicating
Close: #229 

fix: Conflicting WSEGVALV-es

---

documentation/package.json
documentation/yarn.lock

build: Update dependencies

---

documentation/package.json
documentation/yarn.lock

build: Update major version on vulnerable dependencies

---

.pre-commit-config.yaml
completor/prepare_outputs.py
poetry.lock
pyproject.toml
tests/completor/data/wsegdensity_A1_1.true
tests/completor/data/wsegdensity_A1_2.true

refactor: Format to black before writing
